{{- if .Values.bribedPlayer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bribed
  labels:
    app: {{ .Release.Name }}-bribed
    app.kubernetes.io/name: {{ .Release.Name }}-bribed
    app.kubernetes.io/instance: {{ .Release.Name }}-bribed
    service.istio.io/canonical-name: {{ .Release.Name }}-bribed
    service.istio.io/canonical-revision: "v1"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-bribed
{{- end }}
