{{- if .Values.bribedPlayer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bribed
  labels:
    app: {{ .Release.Name }}-bribed
    app.kubernetes.io/name: {{ .Release.Name }}-bribed
    app.kubernetes.io/instance: {{ .Release.Name }}-bribed
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: player-bribed
spec:
  replicas: {{ .Values.bribedPlayer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bribed
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-bribed
        sidecar.istio.io/inject: {{ .Values.istio.inject | quote }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: {{ .Chart.Name }}-bribed
          image: "{{ .Values.bribedPlayer.image.repository | default .Values.image.repository }}:{{ .Values.bribedPlayer.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.bribedPlayer.image.pullPolicy | default .Values.image.pullPolicy }}
          env:
            - name: PLAYER_NAME
              value: "{{ .Values.playerName }}-bribed"
            - name: PORT
              value: "{{ .Values.service.port }}"
            - name: ARTIFICIAL_DELAY_MS
              value: "{{ .Values.bribedPlayer.delayMs }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- end }}
