apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tournament-gateway
  namespace: player-demo
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "162.38.112.167"
      allowedRoutes:
        namespaces:
          from: All
